logger:
    level: DEBUG
oauth:
    client-id: sample-auth-client-id
    client-secret: 50032493-cda1-4237-8c69-d6470b9699a3
    redirect-url: http://auth-proxy:8079/oauth/callback
    scopes:
        - profile
        - email
services:
    auth-proxy:
        host: auth-proxy
        port: 8079
    auth-service:
        host: http://keycloak
        port: :8080
        discovery-url: /auth/realms/
    realm-service:
        redirect-url: /realm/identification
