logger:
    level: DEBUG
oauth:
    client-id: sample-auth-client-id
    client-secret: some-uuid-secret
    redirect-url: /oauth/callback
    resources:
    - uri: /admin/*
      methods:
      - GET
      roles:
      - admin
    scopes:
        - profile
        - email
    url: /oauth/
server:
    host: auth-proxy
    port: :8079
services:
    auth-service:
        host: http://keycloak
        port: :8080
        discovery-url: /auth/realms/
    realm-service:
        redirect-url: /realm/identification
    upstream:
        host: target-service
        port: 8080
